### ISSUE TITLE
Drivetrain - Fine Tune Swerve

### ISSUE THREAD

**Issue by AsherN-chuck** [chuck2147/offseason-2021#3] opened 2021-07-18 18:46 UTC
We need to tune the Mk3 swerve modules as well as make them spin faster so our drivers can have a better time driving and don't waste as much time trying to move around. We can fix this issue by looking at offsets and the swerve code to see if there are any inconsistences within our code.

**Comment by calebeby** [comment] 2021-07-19 01:28
Specific problems we've noticed as compared with other swerves:

- [ ] The max rotation speed is really slow
- [ ] The robot sometimes moves even if you are not touching the controller. This is because some of the controllers do not give a 0 value in the middle. This isn't a software problem but we should address it by testing out the controllers and finding ones that work good, or buying some.
- [ ] If you drive the robot without touching the rotation joystick, the robot turns a lot anyways. Some amount of this is normal in swerves, but this is a lot more than normal.
- [ ] Offsets aren't perfect (like @AsherN-chuck mentioned)
- [ ] If you push _only_ the rotation joystick, the expected behavior is that the wheels form a perfect circle, so the robot can spin in place while minimizing scrubbing. When we do this, the wheels don't form a perfect circle, so some amount of scrubbing still happens.

**Comment by BrockPopek** [comment] 2021-11-19 04:50
The swerve drive was good for the competition.  Closing the item out.

**Closed by BrockPopek** 2021-11-19 04:50 UTC
Labels: enhancement, Low Priority
